/*
* generated by Xtext
*/
package com.tw.demo.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class HKDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
