/*
* generated by Xtext
*/
package com.tw.demo.ui.contentassist;

import com.tw.demo.ui.contentassist.AbstractHKDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HKDslProposalProvider extends AbstractHKDslProposalProvider {

}
