/*
 * generated by Xtext
 */
package com.tw.demo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HKDslUiModule extends com.tw.demo.ui.AbstractHKDslUiModule {
	public HKDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
