/*
 * generated by Xtext
 */
package com.tw.demo;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HKDslRuntimeModule extends com.tw.demo.AbstractHKDslRuntimeModule {

}
